FROM yle-nginx-clojure

COPY conf/test-site.html /usr/local/test-site/index.html

COPY conf/test-site.nginx /etc/nginx/sites-available/yle-nginx-test
RUN ln -s /etc/nginx/sites-available/yle-nginx-test /etc/nginx/sites-enabled/

ADD https://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.jar \
    /usr/lib/nginx/jars/
RUN chmod 0644 /usr/lib/nginx/jars/*.jar
